version: '3.9'

services:
  db:
    container_name: gemini-pg
    image: postgres
    ports:
      - "5432:5432"
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=docker
     - POSTGRES_DB=gemini-api
     - PGDATA=/data/postgres
    volumes:
      - db:/var/lib/postgresql/data

  app:
    depends_on:
      - db
    env_file:
      - .env
    build: .
    ports:
      - "3000:3000"
    environment:
     - GEMINI_API_KEY=${GEMINI_API_KEY}
    command: >
      sh -c "
        npx prisma generate &&
        npx prisma migrate deploy &&
        node seed.js &&
        npm run start
      "
volumes:
  db: